<?php
/**
 * Created by PhpStorm.
 * User: chams
 * Date: 06/12/17
 * Time: 19:21
 */

namespace App\Http\Resources;


use Illuminate\Http\Resources\Json\ResourceCollection;

class UsersCollectionResource extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}