<?php

namespace App\Http\Resources;


use Illuminate\Http\Resources\Json\Resource;

class UserResource extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}