<?php
/**
 * JobResource.php
 * Project: nuntius
 */

namespace Selenkeys\Contacts\App\Http\Resources\Jobs;


use Illuminate\Http\Resources\Json\Resource;

class JobResource extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}