<?php
/**
 * JobsCollectionResource.php
 * Project: nuntius
 */

namespace Selenkeys\Contacts\App\Http\Resources\Jobs;


use Illuminate\Http\Resources\Json\ResourceCollection;

class JobsCollectionResource extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}