<?php
/**
 * ControllerResource.php
 * Project: nuntius
 */

namespace Selenkeys\Contacts\App\Http\Resources\Contacts;


use Illuminate\Http\Resources\Json\Resource;

class ControllerResource extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}